name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Lint extension
      run: npm run lint
    - name: Run tests
      run: npm test
    - name: Build extension
      run: npm run build
    - uses: actions/upload-artifact@v6
      with:
        name: title-tamer-xpi
        path: web-ext-artifacts/*.zip
